### ISSUE TITLE
matchesSelector missing, loading with Webpack

### ISSUE THREAD

**Issue by marcfalk** [metafizzy/flickity#338]
I am using `flickity.pkgd.min.js` v. 1.1.1 in a Webpack setup and have run into a few issues. I have this as my loader: `{ test: require.resolve('flickity'), loader: 'imports?define=>false&this=>window' }` and import of `flickity` resolves to `node_modules/flickity/dist/flickity.pkgd.min.js`. It works perfectly in most browsers, however, I experience a few issues in some.

---

TypeError: Cannot read property 'matches' of null
at apply(raven.js:253:28)
at apply(~/flickity/dist/flickity.pkgd.min.js:13:24667)
at progress(~/flickity/dist/flickity.pkgd.min.js:13:24922)
at emit(~/flickity/dist/flickity.pkgd.min.js:12:4011)
at emitEvent(~/flickity/dist/flickity.pkgd.min.js:12:3753)
at apply(~/flickity/dist/flickity.pkgd.min.js:13:27485)
at getParentCell(~/flickity/dist/flickity.pkgd.min.js:12:23211)
at getParent(~/flickity/dist/flickity.pkgd.min.js:12:10720)
at i(~/flickity/dist/flickity.pkgd.min.js:12:8665)

browser = Chrome 48.0
os = Mac OS X 10.11.3
url = https://www.zetland.dk/blivmedlem
agent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

---

TypeError: Object doesn't support property or method 'msMatchesSelector'
at this(~/flickity/dist/flickity.pkgd.min.js:12:26816)
at this(~/flickity/dist/flickity.pkgd.min.js:12:28672)
at this(~/flickity/dist/flickity.pkgd.min.js:12:28866)
at this(~/flickity/dist/flickity.pkgd.min.js:13:4023)
at this(~/flickity/dist/flickity.pkgd.min.js:12:31876)
at this(~/flickity/dist/flickity.pkgd.min.js:13:802)
at i.prototype.staticClick(~/flickity/dist/flickity.pkgd.min.js:13:6528)
at u.prototype.getParentCell(~/flickity/dist/flickity.pkgd.min.js:12:23211)
at i.getParent(~/flickity/dist/flickity.pkgd.min.js:12:10720)
at n(~/flickity/dist/flickity.pkgd.min.js:12:8665)

browser = IE Mobile 11.0
os = Windows Phone 8.1
url = https://www.zetland.dk
agent = Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 635) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537

---

TypeError: Egenskaben 'msMatchesSelector' kan ikke hentes for reference, der er udefineret eller null
  at c(raven.js:253:16)
  at Anonymous function(~/flickity/dist/flickity.pkgd.min.js:13:24667)
  at e(~/flickity/dist/flickity.pkgd.min.js:13:24922)
  at this(~/flickity/dist/flickity.pkgd.min.js:12:4011)
  at o.emitEvent(~/flickity/dist/flickity.pkgd.min.js:12:3753)
  at r(~/flickity/dist/flickity.pkgd.min.js:13:27485)
  at u.prototype.getParentCell(~/flickity/dist/flickity.pkgd.min.js:12:23211)
  at i.getParent(~/flickity/dist/flickity.pkgd.min.js:12:10720)
  at n(~/flickity/dist/flickity.pkgd.min.js:12:8665)

browser = IE 11.0
os = Windows 10
url = https://www.zetland.dk/blivmedlem
agent = Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; rv:11.0) like Gecko

---

TypeError: Unable to get property 'webkitMatchesSelector' of undefined or null reference
  at c(raven.js:253:16)
  at Anonymous function(~/flickity/dist/flickity.pkgd.min.js:13:24667)
  at e(~/flickity/dist/flickity.pkgd.min.js:13:24922)
  at this(~/flickity/dist/flickity.pkgd.min.js:12:4011)
  at o.emitEvent(~/flickity/dist/flickity.pkgd.min.js:12:3753)
  at i(~/flickity/dist/flickity.pkgd.min.js:13:27485)
  at u.prototype.getParentCell(~/flickity/dist/flickity.pkgd.min.js:12:23211)
  at i.getParent(~/flickity/dist/flickity.pkgd.min.js:12:10720)
  at n(~/flickity/dist/flickity.pkgd.min.js:12:8665)

browser = Edge 13.10586
os = Windows 10
url = https://www.zetland.dk/redaktionen
agent = Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; rv:11.0) like Gecko

---

I use [getsentry.com](http://www.getsentry.com) for JS error reporting and their library is `raven.js`.

I have tried experimenting with different ways of including flickity in my webpack setup, but I'm not sure that that's the issue here. Any hint on what to do?

Thanks,
Marc

**Comment by desandro** [comment]
Looking at the error, It may not be a problem with Webpack or module loading, but how Flickity is being used. Can you check that you are initializing Flickity on a valid element?  Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/flickity/blob/master/contributing.md#submitting-issues).

**Comment by marcfalk** [comment]
We're using Flickity with React, which might cause elements to disappear when Flickity has been initialized on them, although we've made sure to destroy() before unloading the very same elements. Anyway, I'll make a test case. Thanks for replying.

**Comment by splurtcake** [comment]
@marcfalk did you ever overcome this issue? I'm experiencing the same problem at the moment except with Angular 2.
